name: 🌱 Setup
description: Setup the project CI environment

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.15.9
        run_install: false

    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"

    - name: Copy env
      shell: bash
      run: |
        set -e
        cp ./apps/server/.env.example ./apps/server/.env
        cp ./apps/expo/.env.example ./apps/expo/.env
        cp ./jobs/espn-schema/.env.example ./jobs/espn-schema/.env
        cp ./jobs/leaderboard-sync/.env.example ./jobs/leaderboard-sync/.env
        cp ./packages/putting-pals-db/.env.example ./packages/putting-pals-db/.env

    - name: Install deps
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Run codegen
      shell: bash
      run: pnpm codegen
