name: 🌱 Setup

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.12.3
        run_install: false

    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"

    - name: Copy env
      shell: bash
      run: cp ./apps/server/.env.example ./apps/server/.env && cp ./apps/web/.env.example ./apps/web/.env

    - name: Install deps
      shell: bash
      run: pnpm install --frozen-lockfile
