packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@apollo/datasource-rest": ^6.3.0 # https://www.npmjs.com/package/@apollo/datasource-rest?activeTab=versions
  "@eslint/compat": ^1.2.3 # https://www.npmjs.com/package/@eslint/compat?activeTab=versions
  "@fastify/cors": ^10.0.1 # https://www.npmjs.com/package/@fastify/cors?activeTab=versions
  "@fastify/rate-limit": ^10.2.1 # https://www.npmjs.com/package/@fastify/rate-limit?activeTab=versions
  "@ianvs/prettier-plugin-sort-imports": ^4.4.0 # https://www.npmjs.com/package/@ianvs/prettier-plugin-sort-imports?activeTab=versions
  "@ionic/react": ^8.4.1 # https://www.npmjs.com/package/@ionic/react?activeTab=versions
  "@ionic/react-router": ^8.4.1 # https://www.npmjs.com/package/@ionic/react-router?activeTab=versions
  "@mgcrea/fastify-request-logger": ^1.9.0 # https://www.npmjs.com/package/@mgcrea/fastify-request-logger?activeTab=versions
  "@mgcrea/pino-pretty-compact": ^1.4.2 # https://www.npmjs.com/package/@mgcrea/pino-pretty-compact?activeTab=versions
  "@radix-ui/react-avatar": ^1.1.1 # https://www.npmjs.com/package/@radix-ui/react-avatar?activeTab=versions
  "@sentry/react": ^8.41.0 # https://www.npmjs.com/package/@sentry/react?activeTab=versions
  "@sentry/vite-plugin": ^2.22.6 # https://www.npmjs.com/package/@sentry/vite-plugin?activeTab=versions
  "@storybook/addon-a11y": ^8.4.5 # https://www.npmjs.com/package/@storybook/addon-a11y?activeTab=versions
  "@storybook/addon-essentials": ^8.4.5 # https://www.npmjs.com/package/@storybook/addon-essentials?activeTab=versions
  "@storybook/addon-themes": ^8.4.5 # https://www.npmjs.com/package/@storybook/addon-themes?activeTab=versions
  "@storybook/blocks": ^8.4.5 # https://www.npmjs.com/package/@storybook/blocks?activeTab=versions
  "@storybook/react": ^8.4.5 # https://www.npmjs.com/package/@storybook/react?activeTab=versions
  "@storybook/react-vite": ^8.4.5 # https://www.npmjs.com/package/@storybook/react-vite?activeTab=versions
  "@storybook/theming": ^8.4.5 # https://www.npmjs.com/package/@storybook/theming?activeTab=versions
  "@tanstack/react-query": ^5.61.5 # https://www.npmjs.com/package/@tanstack/react-query?activeTab=versions
  "@testing-library/dom": ^10.4.0 # https://www.npmjs.com/package/@testing-library/dom?activeTab=versions
  "@testing-library/jest-dom": ^6.6.3 # https://www.npmjs.com/package/@testing-library/jest-dom?activeTab=versions
  "@testing-library/react": ^16.0.1 # https://www.npmjs.com/package/@testing-library/react?activeTab=versions
  "@total-typescript/tsconfig": ^1.0.4 # https://www.npmjs.com/package/@total-typescript/tsconfig?activeTab=versions
  "@trpc/client": ^11.0.0-rc.648 # https://www.npmjs.com/package/@trpc/client?activeTab=versions
  "@trpc/react-query": ^11.0.0-rc.648 # https://www.npmjs.com/package/@trpc/react-query?activeTab=versions
  "@trpc/server": ^11.0.0-rc.648 # https://www.npmjs.com/package/@trpc/server?activeTab=versions
  "@types/lodash": ^4.17.16 # https://www.npmjs.com/package/@types/lodash?activeTab=versions
  "@types/node": ^22.9.3 # https://www.npmjs.com/package/@types/node?activeTab=versions
  "@types/pako": ^2.0.3 # https://www.npmjs.com/package/@types/pako?activeTab=versions
  "@types/react": ^18.3.12 # https://www.npmjs.com/package/@types/react?activeTab=versions
  "@types/react-dom": ^18.3.1 # https://www.npmjs.com/package/@types/react-dom?activeTab=versions
  "@types/react-router": ^5.1.20 # https://www.npmjs.com/package/@types/react-router?activeTab=versions
  "@types/react-router-dom": ^5.3.3 # https://www.npmjs.com/package/@types/react-router-dom?activeTab=versions
  "@vite-pwa/assets-generator": ^0.2.6 # https://www.npmjs.com/package/@vite-pwa/assets-generator?activeTab=versions
  "@vitejs/plugin-react-swc": ^3.7.2 # https://www.npmjs.com/package/@vitejs/plugin-react-swc?activeTab=versions
  autoprefixer: ^10.4.20 # https://www.npmjs.com/package/autoprefixer?activeTab=versions
  cheerio: ^1.0.0 # https://www.npmjs.com/package/cheerio?activeTab=versions
  class-variance-authority: ^0.7.1 # https://www.npmjs.com/package/class-variance-authority?activeTab=versions
  clsx: ^2.1.1 # https://www.npmjs.com/package/clsx?activeTab=versions
  dotenv: ^16.4.5 # https://www.npmjs.com/package/dotenv?activeTab=versions
  eslint: 9.14.0 # https://www.npmjs.com/package/eslint?activeTab=versions TODO: update to 9.15.0 when 'Cannot read properties of undefined (reading 'allowShortCircuit')' bug is fixed
  eslint-plugin-import: ^2.31.0 # https://www.npmjs.com/package/eslint-plugin-import?activeTab=versions
  eslint-plugin-jsx-a11y: ^6.10.2 # https://www.npmjs.com/package/eslint-plugin-jsx-a11y?activeTab=versions
  eslint-plugin-react: ^7.37.2 # https://www.npmjs.com/package/eslint-plugin-react?activeTab=versions
  eslint-plugin-react-hooks: ^5.0.0 # https://www.npmjs.com/package/eslint-plugin-react-hooks?activeTab=versions
  eslint-plugin-storybook: ^0.11.1 # https://www.npmjs.com/package/eslint-plugin-storybook?activeTab=versions
  eslint-plugin-turbo: ^2.3.3 # https://www.npmjs.com/package/eslint-plugin-turbo?activeTab=versions
  fastify: ^5.1.0 # https://www.npmjs.com/package/fastify?activeTab=versions
  globals: ^15.12.0 # https://www.npmjs.com/package/globals?activeTab=versions
  ionicons: ^7.4.0 # https://www.npmjs.com/package/ionicons?activeTab=versions
  jsdom: ^25.0.1 # https://www.npmjs.com/package/jsdom?activeTab=versions
  lucide-react: ^0.462.0 # https://www.npmjs.com/package/lucide-react?activeTab=versions
  lodash: ^4.17.21 # https://www.npmjs.com/package/lodash?activeTab=versions
  pako: ^2.1.0 # https://www.npmjs.com/package/pako?activeTab=versions
  pino: ^9.5.0 # https://www.npmjs.com/package/pino?activeTab=versions
  pino-pretty: ^13.0.0 # https://www.npmjs.com/package/pino-pretty?activeTab=versions
  postcss: ^8.4.49 # https://www.npmjs.com/package/postcss?activeTab=versions
  prettier: ^3.4.1 # https://www.npmjs.com/package/prettier?activeTab=versions
  prettier-plugin-tailwindcss: ^0.6.9 # https://www.npmjs.com/package/prettier-plugin-tailwindcss?activeTab=versions
  react: ^18.3.1 # https://www.npmjs.com/package/react?activeTab=versions
  react-dom: ^18.3.1 # https://www.npmjs.com/package/react-dom?activeTab=versions
  react-router: ^5.3.4 # https://www.npmjs.com/package/react-router?activeTab=versions
  react-router-dom: ^5.3.4 # https://www.npmjs.com/package/react-router-dom?activeTab=versions
  storybook: ^8.4.5 # https://www.npmjs.com/package/storybook?activeTab=versions
  superjson: ^2.2.1 # https://www.npmjs.com/package/superjson?activeTab=versions
  tailwind-merge: ^2.5.5 # https://www.npmjs.com/package/tailwind-merge?activeTab=versions
  tailwindcss: ^3.4.15 # https://www.npmjs.com/package/tailwindcss?activeTab=versions
  tailwindcss-animate: ^1.0.7 # https://www.npmjs.com/package/tailwindcss-animate?activeTab=versions
  turbo: ^2.5.6 # https://www.npmjs.com/package/turbo?activeTab=versions
  typescript: ^5.7.2 # https://www.npmjs.com/package/typescript?activeTab=versions
  typescript-eslint: ^8.16.0 # https://www.npmjs.com/package/typescript-eslint?activeTab=versions
  vite: ^5.4.11 # https://www.npmjs.com/package/vite?activeTab=versions
  vite-plugin-node: ^4.0.0 # https://www.npmjs.com/package/vite-plugin-node?activeTab=versions
  vite-plugin-pwa: ^0.21.1 # https://www.npmjs.com/package/vite-plugin-pwa?activeTab=versions
  vite-tsconfig-paths: ^5.1.3 # https://www.npmjs.com/package/vite-tsconfig-paths?activeTab=versions
  vitest: ^2.1.6 # https://www.npmjs.com/package/vitest?activeTab=versions
  zod: ^3.23.8 # https://www.npmjs.com/package/zod?activeTab=versions
  workbox-window: ^7.3.0 # https://www.npmjs.com/package/workbox-window?activeTab=versions
