packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@total-typescript/tsconfig": ^1.0.4
  "@trpc/server": ^11.7.2
  "@types/node": ^24.10.1
  dotenv: ^17.2.3
  superjson: ^2.2.5
  typescript: ^5.9.3
  zod: ^4.1.13
