packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@biomejs/biome": ^2.3.7
  "@total-typescript/tsconfig": ^1.0.4
  "@trpc/server": ^11.7.1
  "@types/node": ^24.4.0
  superjson: ^2.2.2
  typescript: ^5.9.3
  zod: ^4.1.12
