packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@total-typescript/tsconfig": ^1.0.4 # https://www.npmjs.com/package/@total-typescript/tsconfig?activeTab=versions
  "@trpc/server": ^11.7.1 # https://www.npmjs.com/package/@trpc/server?activeTab=versions
  "@types/node": ^24.4.0 # https://www.npmjs.com/package/@types/node?activeTab=versions
  eslint: ^9.38.0 # https://www.npmjs.com/package/eslint?activeTab=versions
  prettier: ^3.6.2 # https://www.npmjs.com/package/prettier?activeTab=versions
  superjson: ^2.2.2 # https://www.npmjs.com/package/superjson?activeTab=versions
  typescript: ^5.9.3 # https://www.npmjs.com/package/typescript?activeTab=versions
  zod: ^4.1.12 # https://www.npmjs.com/package/zod?activeTab=versions
