packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@apollo/datasource-rest": ^6.3.0
  "@eslint/compat": ^1.2.3
  "@fastify/cors": ^10.0.1
  "@fastify/rate-limit": ^10.2.1
  "@ianvs/prettier-plugin-sort-imports": ^4.4.0
  "@ionic/react": ^8.4.1
  "@ionic/react-router": ^8.4.1
  "@mgcrea/fastify-request-logger": ^1.9.0
  "@mgcrea/pino-pretty-compact": ^1.4.2
  "@radix-ui/react-avatar": ^1.1.1
  "@sentry/react": ^8.41.0
  "@sentry/vite-plugin": ^2.22.6
  "@storybook/addon-a11y": ^8.4.5
  "@storybook/addon-essentials": ^8.4.5
  "@storybook/addon-themes": ^8.4.5
  "@storybook/blocks": ^8.4.5
  "@storybook/react": ^8.4.5
  "@storybook/react-vite": ^8.4.5
  "@storybook/theming": ^8.4.5
  "@tanstack/react-query": ^5.61.5
  "@testing-library/dom": ^10.4.0
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/react": ^16.0.1
  "@total-typescript/tsconfig": ^1.0.4
  "@trpc/client": ^11.0.0-rc.648
  "@trpc/react-query": ^11.0.0-rc.648
  "@trpc/server": ^11.0.0-rc.648
  "@types/lodash": ^4.17.16
  "@types/node": ^22.9.3
  "@types/pako": ^2.0.3
  "@types/react": ^18.3.12
  "@types/react-dom": ^18.3.1
  "@types/react-router": ^5.1.20
  "@types/react-router-dom": ^5.3.3
  "@vite-pwa/assets-generator": ^0.2.6
  "@vitejs/plugin-react-swc": ^3.7.2
  autoprefixer: ^10.4.20
  cheerio: ^1.0.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dotenv: ^16.4.5
  eslint: 9.14.0
  eslint-plugin-import: ^2.31.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.2
  eslint-plugin-react-hooks: ^5.0.0
  eslint-plugin-storybook: ^0.11.1
  eslint-plugin-turbo: ^2.3.3
  fastify: ^5.1.0
  globals: ^15.12.0
  ionicons: ^7.4.0
  jsdom: ^25.0.1
  lodash: ^4.17.21
  lucide-react: ^0.462.0
  pako: ^2.1.0
  pino: ^9.5.0
  pino-pretty: ^13.0.0
  postcss: ^8.4.49
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.9
  react: ^18.3.1
  react-dom: ^18.3.1
  react-router: ^5.3.4
  react-router-dom: ^5.3.4
  storybook: ^8.4.5
  superjson: ^2.2.1
  tailwind-merge: ^2.5.5
  tailwindcss: ^3.4.15
  tailwindcss-animate: ^1.0.7
  turbo: ^2.5.6
  typescript: ^5.9.2
  typescript-eslint: ^8.16.0
  vite: ^5.4.11
  vite-plugin-node: ^4.0.0
  vite-plugin-pwa: ^0.21.1
  vite-tsconfig-paths: ^5.1.3
  vitest: ^2.1.9
  workbox-window: ^7.3.0
  zod: ^3.23.8
