packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@apollo/datasource-rest": ^6.4.1
  "@eslint/compat": ^1.3.2
  "@fastify/cors": ^11.1.0
  "@fastify/rate-limit": ^10.3.0
  "@ianvs/prettier-plugin-sort-imports": ^4.7.0
  "@ionic/react": ^8.7.3
  "@ionic/react-router": ^8.7.3
  "@mgcrea/fastify-request-logger": ^1.9.1
  "@mgcrea/pino-pretty-compact": ^1.4.2
  "@radix-ui/react-avatar": ^1.1.1
  "@sentry/react": ^10.11.0
  "@sentry/vite-plugin": ^4.3.0
  "@storybook/addon-a11y": ^8.4.2
  "@storybook/addon-essentials": ^8.4.2
  "@storybook/addon-themes": ^8.4.2
  "@storybook/blocks": ^8.4.2
  "@storybook/react": ^8.4.2
  "@storybook/react-vite": ^8.4.2
  "@storybook/theming": ^8.4.2
  "@tanstack/react-query": ^5.87.4
  "@testing-library/dom": ^10.4.1
  "@testing-library/jest-dom": ^6.8.0
  "@testing-library/react": ^16.3.0
  "@total-typescript/tsconfig": ^1.0.4
  "@trpc/client": ^11.5.1
  "@trpc/react-query": ^11.5.1
  "@trpc/server": ^11.5.1
  "@types/lodash": ^4.17.20
  "@types/node": ^24.4.0
  "@types/pako": ^2.0.4
  "@types/react": ~19.1.0
  "@types/react-dom": ^19.1.9
  "@types/react-router": ^5.1.20
  "@types/react-router-dom": ^5.3.3
  "@vite-pwa/assets-generator": ^1.0.1
  "@vitejs/plugin-react": ^5.0.4
  autoprefixer: ^10.4.21
  cheerio: ^1.1.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dotenv: ^17.2.2
  eslint: ^9.25.0
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-storybook: ^0.11.0
  eslint-plugin-turbo: ^2.5.6
  fastify: ^5.6.0
  globals: ^16.4.0
  ionicons: ^8.0.13
  jsdom: ^27.0.0
  lodash: ^4.17.21
  lucide-react: ^0.544.0
  pako: ^2.1.0
  pino: ^9.9.5
  pino-pretty: ^13.1.1
  postcss: ^8.5.6
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  react: 19.1.0
  react-dom: 19.1.0
  react-router: ^5.3.4
  react-router-dom: ^5.3.4
  storybook: ^8.4.2
  superjson: ^2.2.2
  tailwind-merge: ^3.3.1
  tailwindcss: ^3.4.17
  tailwindcss-animate: ^1.0.7
  terser: ^5.44.0
  turbo: ^2.5.6
  typescript: ~5.9.2
  typescript-eslint: ^8.43.0
  vite: ^7.1.5
  vite-plugin-node: ^7.0.0
  vite-plugin-pwa: ^1.0.3
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  workbox-window: ^7.3.0
  zod: ^4.1.8
