packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@apollo/datasource-rest": ^6.3.0 # https://www.npmjs.com/package/@apollo/datasource-rest?activeTab=versions
  "@eslint/compat": ^1.2.2 # https://www.npmjs.com/package/@eslint/compat?activeTab=versions
  "@fastify/cors": ^10.0.1 # https://www.npmjs.com/package/@fastify/cors?activeTab=versions
  "@fastify/rate-limit": ^10.1.1 # https://www.npmjs.com/package/@fastify/rate-limit?activeTab=versions
  "@headlessui/react": ^2.2.0 # https://www.npmjs.com/package/@headlessui/react?activeTab=versions
  "@heroicons/react": ^2.1.5 # https://www.npmjs.com/package/@heroicons/react?activeTab=versions
  "@ianvs/prettier-plugin-sort-imports": ^4.4.0 # https://www.npmjs.com/package/@ianvs/prettier-plugin-sort-imports?activeTab=versions
  "@ionic/react": ^8.4.0 # https://www.npmjs.com/package/@ionic/react?activeTab=versions
  "@ionic/react-router": ^8.4.0 # https://www.npmjs.com/package/@ionic/react-router?activeTab=versions
  "@mgcrea/fastify-request-logger": ^1.8.0 # https://www.npmjs.com/package/@mgcrea/fastify-request-logger?activeTab=versions
  "@mgcrea/pino-pretty-compact": ^1.3.0 # https://www.npmjs.com/package/@mgcrea/pino-pretty-compact?activeTab=versions
  "@nextui-org/button": ^2.0.38 # https://www.npmjs.com/package/@nextui-org/button?activeTab=versions
  "@nextui-org/card": ^2.0.34 # https://www.npmjs.com/package/@nextui-org/card?activeTab=versions
  "@nextui-org/image": ^2.0.32 # https://www.npmjs.com/package/@nextui-org/image?activeTab=versions
  "@nextui-org/system": ^2.2.6 # https://www.npmjs.com/package/@nextui-org/system?activeTab=versions
  "@nextui-org/theme": ^2.2.11 # https://www.npmjs.com/package/@nextui-org/theme?activeTab=versions
  "@radix-ui/react-slot": ^1.1.0 # https://www.npmjs.com/package/@radix-ui/react-slot?activeTab=versions
  "@sentry/node": ^8.37.1 # https://www.npmjs.com/package/@sentry/node?activeTab=versions
  "@sentry/profiling-node": ^8.37.1 # https://www.npmjs.com/package/@sentry/profiling-node?activeTab=versions
  "@sentry/react": ^8.37.1 # https://www.npmjs.com/package/@sentry/react?activeTab=versions
  "@sentry/vite-plugin": ^2.22.6 # https://www.npmjs.com/package/@sentry/vite-plugin?activeTab=versions
  "@storybook/addon-a11y": ^8.4.2 # https://www.npmjs.com/package/@storybook/addon-a11y?activeTab=versions
  "@storybook/addon-essentials": ^8.4.2 # https://www.npmjs.com/package/@storybook/addon-essentials?activeTab=versions
  "@storybook/addon-themes": ^8.4.2 # https://www.npmjs.com/package/@storybook/addon-themes?activeTab=versions
  "@storybook/blocks": ^8.4.2 # https://www.npmjs.com/package/@storybook/blocks?activeTab=versions
  "@storybook/react": ^8.4.2 # https://www.npmjs.com/package/@storybook/react?activeTab=versions
  "@storybook/react-vite": ^8.4.2 # https://www.npmjs.com/package/@storybook/react-vite?activeTab=versions
  "@storybook/theming": ^8.4.2 # https://www.npmjs.com/package/@storybook/theming?activeTab=versions
  "@tanstack/react-query": ^5.59.20 # https://www.npmjs.com/package/@tanstack/react-query?activeTab=versions
  "@testing-library/dom": ^10.4.0 # https://www.npmjs.com/package/@testing-library/dom?activeTab=versions
  "@testing-library/jest-dom": ^6.6.3 # https://www.npmjs.com/package/@testing-library/jest-dom?activeTab=versions
  "@testing-library/react": ^16.0.1 # https://www.npmjs.com/package/@testing-library/react?activeTab=versions
  "@total-typescript/tsconfig": ^1.0.4 # https://www.npmjs.com/package/@total-typescript/tsconfig?activeTab=versions
  "@trpc/client": ^11.0.0-rc.630 # https://www.npmjs.com/package/@trpc/client?activeTab=versions
  "@trpc/react-query": ^11.0.0-rc.630 # https://www.npmjs.com/package/@trpc/react-query?activeTab=versions
  "@trpc/server": ^11.0.0-rc.630 # https://www.npmjs.com/package/@trpc/server?activeTab=versions
  "@types/node": ^22.9.0 # https://www.npmjs.com/package/@types/node?activeTab=versions
  "@types/react": ^18.3.12 # https://www.npmjs.com/package/@types/react?activeTab=versions
  "@types/react-dom": ^18.3.1 # https://www.npmjs.com/package/@types/react-dom?activeTab=versions
  "@types/react-router": ^5.1.20 # https://www.npmjs.com/package/@types/react-router?activeTab=versions
  "@types/react-router-dom": ^5.3.3 # https://www.npmjs.com/package/@types/react-router-dom?activeTab=versions
  "@vitejs/plugin-react-swc": ^3.7.1 # https://www.npmjs.com/package/@vitejs/plugin-react-swc?activeTab=versions
  autoprefixer: ^10.4.20 # https://www.npmjs.com/package/autoprefixer?activeTab=versions
  class-variance-authority: ^0.7.0 # https://www.npmjs.com/package/class-variance-authority?activeTab=versions
  clsx: ^2.1.1 # https://www.npmjs.com/package/clsx?activeTab=versions
  dotenv: ^16.4.5 # https://www.npmjs.com/package/dotenv?activeTab=versions
  drizzle-kit: ^0.28.0 # https://www.npmjs.com/package/drizzle-kit?activeTab=versions
  drizzle-orm: ^0.36.1 # https://www.npmjs.com/package/drizzle-orm?activeTab=versions
  eslint: 9.14.0 # https://www.npmjs.com/package/eslint?activeTab=versions TODO: update to 9.15.0 when 'Cannot read properties of undefined (reading 'allowShortCircuit')' bug is fixed
  eslint-plugin-import: ^2.31.0 # https://www.npmjs.com/package/eslint-plugin-import?activeTab=versions
  eslint-plugin-jsx-a11y: ^6.10.2 # https://www.npmjs.com/package/eslint-plugin-jsx-a11y?activeTab=versions
  eslint-plugin-react: ^7.37.2 # https://www.npmjs.com/package/eslint-plugin-react?activeTab=versions
  eslint-plugin-react-hooks: ^5.0.0 # https://www.npmjs.com/package/eslint-plugin-react-hooks?activeTab=versions
  eslint-plugin-storybook: ^0.11.0 # https://www.npmjs.com/package/eslint-plugin-storybook?activeTab=versions
  eslint-plugin-turbo: ^2.2.3 # https://www.npmjs.com/package/eslint-plugin-turbo?activeTab=versions
  fastify: ^5.1.0 # https://www.npmjs.com/package/fastify?activeTab=versions
  framer-motion: ^11.11.11 # https://www.npmjs.com/package/framer-motion?activeTab=versions
  globals: ^15.12.0 # https://www.npmjs.com/package/globals?activeTab=versions
  ionicons: ^7.4.0 # https://www.npmjs.com/package/ionicons?activeTab=versions
  jsdom: ^25.0.1 # https://www.npmjs.com/package/jsdom?activeTab=versions
  lucide-react: ^0.456.0 # https://www.npmjs.com/package/lucide-react?activeTab=versions
  pino: ^9.5.0 # https://www.npmjs.com/package/pino?activeTab=versions
  pino-pretty: ^13.0.0 # https://www.npmjs.com/package/pino-pretty?activeTab=versions
  postcss: ^8.4.49 # https://www.npmjs.com/package/postcss?activeTab=versions
  postgres: ^3.4.5 # https://www.npmjs.com/package/postgres?activeTab=versions
  prettier: ^3.3.3 # https://www.npmjs.com/package/prettier?activeTab=versions
  prettier-plugin-tailwindcss: ^0.6.8 # https://www.npmjs.com/package/prettier-plugin-tailwindcss?activeTab=versions
  react: ^18.3.1 # https://www.npmjs.com/package/react?activeTab=versions
  react-dom: ^18.3.1 # https://www.npmjs.com/package/react-dom?activeTab=versions
  react-router: ^5.3.4 # https://www.npmjs.com/package/react-router?activeTab=versions
  react-router-dom: ^5.3.4 # https://www.npmjs.com/package/react-router-dom?activeTab=versions
  recharts: ^2.13.3 # https://www.npmjs.com/package/recharts?activeTab=versions
  rimraf: ^6.0.1 # https://www.npmjs.com/package/rimraf?activeTab=versions
  storybook: ^8.4.2 # https://www.npmjs.com/package/storybook?activeTab=versions
  superjson: ^2.2.1 # https://www.npmjs.com/package/superjson?activeTab=versions
  tailwind-merge: ^2.5.4 # https://www.npmjs.com/package/tailwind-merge?activeTab=versions
  tailwindcss: ^3.4.14 # https://www.npmjs.com/package/tailwindcss?activeTab=versions
  tailwindcss-animate: ^1.0.7 # https://www.npmjs.com/package/tailwindcss-animate?activeTab=versions
  turbo: ^2.2.3 # https://www.npmjs.com/package/turbo?activeTab=versions
  typescript: ^5.6.3 # https://www.npmjs.com/package/typescript?activeTab=versions
  typescript-eslint: ^8.14.0 # https://www.npmjs.com/package/typescript-eslint?activeTab=versions
  vite: ^5.4.11 # https://www.npmjs.com/package/vite?activeTab=versions
  vite-plugin-node: ^4.0.0 # https://www.npmjs.com/package/vite-plugin-node?activeTab=versions
  vite-plugin-pwa: ^0.21.0 # https://www.npmjs.com/package/vite-plugin-pwa?activeTab=versions
  vite-tsconfig-paths: ^5.1.2 # https://www.npmjs.com/package/vite-tsconfig-paths?activeTab=versions
  vitest: ^2.1.4 # https://www.npmjs.com/package/vitest?activeTab=versions
  zod: ^3.23.8 # https://www.npmjs.com/package/zod?activeTab=versions
