packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@total-typescript/tsconfig": ^1.0.4
  "@trpc/client": ^11.8.0
  "@trpc/server": ^11.8.0
  "@trpc/tanstack-react-query": ^11.8.0
  "@types/node": ^24.10.1
  dotenv: ^17.2.3
  drizzle-orm: ^0.45.1
  fast-json-patch: ^3.1.1
  graphql: ^16.12.0
  graphql-request: ^7.4.0
  superjson: ^2.2.5
  typescript: ^5.9.3
  vitest: ^4.0.14
  zod: ^4.1.13
