import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import z from "zod";
import { CompetitorSchema } from "./src/domain/schemas";
import {
  COMPETITORS,
  INDEX as COMPETITORS_INDEX,
  type CompetitorSlug,
  CompetitorSlugs,
} from "./src/generated/competitors";
import {
  PLAYERS,
  INDEX as PLAYERS_INDEX,
  PlayerSlugs,
} from "./src/generated/players";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = __dirname;

const REPLACEMENTS: Record<string, string> = {
  ø: "o",
  Ø: "O",
  æ: "ae",
  Æ: "AE",
  þ: "th",
  Þ: "TH",
  ð: "d",
  Ð: "D",
  ß: "ss",
  đ: "d",
  Đ: "D",
  ł: "l",
  Ł: "L",
};

function toSlug(displayName: string): string {
  return displayName
    .replace(/[øØæÆþÞðÐßđĐłŁ]/g, (char) => REPLACEMENTS[char] ?? char)
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/[\s-]+/g, "-");
}

function generateCompetitors() {
  const inputPath = path.join(packageRoot, "data/competitors/directory.json");
  const raw = CompetitorSchema.array().parse(
    JSON.parse(fs.readFileSync(inputPath, "utf8")),
  );

  const idx = {} as Record<string, number>;

  raw.forEach((c, i) => {
    idx[toSlug(c.displayName)] = i;
  });

  const out = `/** Generated by codegen. Do not edit. */

export const COMPETITORS = ${JSON.stringify(raw, null, 2)} as const

export const INDEX = ${JSON.stringify(idx, null, 2)} as const

export const CompetitorValues = ${JSON.stringify(
    raw.map((it) => toSlug(it.displayName)),
    null,
    2,
  )} as const

export type CompetitorSlug = keyof typeof INDEX
`;

  const outPath = path.join(packageRoot, "src", "generated", "competitors.ts");
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, out);
}

async function generatePlayers() {
  const playersResponse = await fetch(
    "https://data-api.pgatour.com/player/list/R",
  );
  const playersJson = await playersResponse.json();
  const raw = z
    .object({
      players: z.array(
        z.object({
          id: z.string(),
          displayName: z.string(),
        }),
      ),
    })
    .parse(playersJson);

  const idx = {} as Record<string, number>;

  raw.players.forEach((c, i) => {
    idx[toSlug(c.displayName)] = i;
  });

  const out = `/** Generated by codegen. Do not edit. */

export const PLAYERS = ${JSON.stringify(
    raw.players.map((p) => p.id),
    null,
    2,
  )} as const

export const INDEX = ${JSON.stringify(idx, null, 2)} as const

export const PlayerValues = ${JSON.stringify(
    raw.players.map((it) => toSlug(it.displayName)),
    null,
    2,
  )} as const

export type PlayerSlug = keyof typeof INDEX
`;

  const outPath = path.join(packageRoot, "src", "generated", "players.ts");
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, out);
}

function generateCompetitions() {
  const inputPath = path.join(
    packageRoot,
    "data/competitions/2026/01-masters-tournament.json",
  );
  const raw = z
    .object({
      tournamentId: z.string(),
      paddyPowerId: z.string().nullable(),
      winner: z.enum(CompetitorSlugs).nullable(),
      runnerUp: z.enum(CompetitorSlugs).nullable(),
      competitors: z.partialRecord(
        z.enum(CompetitorSlugs),
        z.array(z.enum(PlayerSlugs)),
      ),
    })
    .parse(JSON.parse(fs.readFileSync(inputPath, "utf8")));

  const resolved = {
    ...raw,
    competitors: Object.entries(raw.competitors).map((it) => {
      return {
        ...COMPETITORS[COMPETITORS_INDEX[it[0] as CompetitorSlug]], // TODO remove cast
        picks: it[1].map((it) => {
          return {
            id: PLAYERS[PLAYERS_INDEX[it]],
            slug: it,
          };
        }),
      };
    }),
  };

  const out = `/** Generated by codegen. Do not edit. */

export const COMPETITIONS = [${JSON.stringify(resolved, null, 2)}] as const
`;

  const outPath = path.join(packageRoot, "src", "generated", "competitions.ts");
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, out);
}

generateCompetitors();
await generatePlayers();
generateCompetitions();
