import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { injectDependencies as injectPgaTourDependencies } from "@putting-pals/pga-tour-api";
import z from "zod";
import { CompetitorSchema } from "./src/domain/schemas";
import {
  COMPETITORS,
  INDEX as COMPETITORS_INDEX,
  type CompetitorSlug,
  CompetitorSlugs,
} from "./src/generated/competitors";
import {
  PLAYERS,
  INDEX as PLAYERS_INDEX,
  PlayerSlugs,
} from "./src/generated/players";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = __dirname;

const REPLACEMENTS: Record<string, string> = {
  ø: "o",
  Ø: "O",
  æ: "ae",
  Æ: "AE",
  þ: "th",
  Þ: "TH",
  ð: "d",
  Ð: "D",
  ß: "ss",
  đ: "d",
  Đ: "D",
  ł: "l",
  Ł: "L",
};

function toSlug(displayName: string): string {
  return displayName
    .replace(/[øØæÆþÞðÐßđĐłŁ]/g, (char) => REPLACEMENTS[char] ?? char)
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/[\s-]+/g, "-");
}

function generateCompetitors() {
  const inputPath = path.join(packageRoot, "data/competitors/directory.json");
  const raw = CompetitorSchema.array().parse(
    JSON.parse(fs.readFileSync(inputPath, "utf8")),
  );

  const idx = {} as Record<string, number>;

  raw.forEach((c, i) => {
    idx[toSlug(c.displayName)] = i;
  });

  const out = `/** Generated by codegen. Do not edit. */

export const COMPETITORS = ${JSON.stringify(raw, null, 2)} as const

export const INDEX = ${JSON.stringify(idx, null, 2)} as const

export const CompetitorSlugs = ${JSON.stringify(
    raw.map((it) => toSlug(it.displayName)),
    null,
    2,
  )} as const

export type CompetitorSlug = keyof typeof INDEX
`;

  const outPath = path.join(packageRoot, "src", "generated", "competitors.ts");
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, out);
}

async function generatePlayers() {
  const pgaTourDependencies = injectPgaTourDependencies();
  const players = pgaTourDependencies.playerClient.getPlayers("pga");

  const idx = {} as Record<string, number>;

  players.forEach((c, i) => {
    idx[toSlug(c.displayName)] = i;
  });

  const out = `/** Generated by codegen. Do not edit. */

export const PLAYERS = ${JSON.stringify(
    players.map((p) => p.id),
    null,
    2,
  )} as const

export const INDEX = ${JSON.stringify(idx, null, 2)} as const

export const PlayerSlugs = ${JSON.stringify(
    players.map((it) => toSlug(it.displayName)),
    null,
    2,
  )} as const

export type PlayerSlug = keyof typeof INDEX
`;

  const outPath = path.join(packageRoot, "src", "generated", "players.ts");
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, out);
}

function generateCompetitions() {
  function findCompetitionFiles(directory: string): string[] {
    const entries = fs.readdirSync(directory, { withFileTypes: true });
    return entries.flatMap((entry) => {
      const fullPath = path.join(directory, entry.name);
      if (entry.isDirectory()) {
        return findCompetitionFiles(fullPath);
      } else if (entry.isFile() && entry.name.endsWith(".json")) {
        return [fullPath];
      } else {
        return [];
      }
    });
  }

  const competitionFilenames = findCompetitionFiles(
    path.join(
      path.dirname(fileURLToPath(import.meta.url)),
      "data",
      "competitions",
    ),
  );

  const raw = competitionFilenames.map((it) =>
    z
      .object({
        tournamentId: z.string(),
        paddyPowerId: z.string().nullable(),
        winner: z.enum(CompetitorSlugs).nullable(),
        runnerUp: z.enum(CompetitorSlugs).nullable(),
        competitors: z.partialRecord(
          z.enum(CompetitorSlugs),
          z.array(z.enum(PlayerSlugs)),
        ),
      })
      .parse(JSON.parse(fs.readFileSync(it, "utf8"))),
  );

  const resolved = raw.map((it) => {
    return {
      ...it,
      competitors: Object.entries(it.competitors).map((it) => {
        return {
          ...COMPETITORS[COMPETITORS_INDEX[it[0] as CompetitorSlug]], // TODO remove cast
          picks: it[1].map((it) => {
            return {
              id: PLAYERS[PLAYERS_INDEX[it]],
              slug: it,
            };
          }),
        };
      }),
    };
  });

  const out = `/** Generated by codegen. Do not edit. */

export const COMPETITIONS = ${JSON.stringify(resolved, null, 2)} as const
`;

  const outPath = path.join(packageRoot, "src", "generated", "competitions.ts");
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, out);
}

generateCompetitors();
await generatePlayers();
generateCompetitions();
