import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import type { CodegenConfig } from "@graphql-codegen/cli";
import { addTypenameSelectionDocumentTransform } from "@graphql-codegen/client-preset";
import z from "zod";

const config: CodegenConfig = {
  generates: {
    "src/generated/graphql.ts": {
      schema: [
        {
          "https://orchestrator.pgatour.com/graphql": {
            headers: {
              "X-Api-Key": "da2-gsrx5bibzbb4njvhl7t37wqyl4",
            },
          },
        },
      ],
      documents: ["src/graphql/**/*.graphql"],
      plugins: [
        "typescript",
        "typescript-operations",
        "typescript-graphql-request",
      ],
      documentTransforms: [addTypenameSelectionDocumentTransform],
      config: {
        addTypename: true,
        enumsAsTypes: true,
        // immutableTypes: true,
        nonOptionalTypename: true,
        printFieldsOnNewLines: true,
        useTypeImports: true,
        scalars: {
          AWSDateTime: {
            input: "string",
            output: "string",
          },
          AWSTimestamp: {
            input: "number",
            output: "number",
          },
        },
        // noExport: true,
        typesPrefix: "Api",
        fragmentPrefix: "Api",
        fragmentVariablePrefix: "Api",
        documentVariablePrefix: "Api",
        documentMode: "documentNode",
      },
    },
  },
};

export default config;

async function generatePlayerDirectory() {
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const packageRoot = __dirname;

  const playersResponse = await fetch(
    "https://data-api.pgatour.com/player/list/R",
  );
  const playersJson = await playersResponse.json();
  const raw = z
    .object({
      players: z.array(
        z.object({
          id: z.string(),
          displayName: z.string(),
        }),
      ),
    })
    .parse(playersJson);

  const inputPath = path.join(packageRoot, "data/players/directory.json");
  const rawHardcoded = z
    .object({
      id: z.string(),
      displayName: z.string(),
    })
    .array()
    .parse(JSON.parse(fs.readFileSync(inputPath, "utf8")));

  raw.players.push(...rawHardcoded);

  const out = `/** Generated by codegen. Do not edit. */

export const PLAYERS = ${JSON.stringify(raw.players, null, 2)}
`;

  const outPath = path.join(packageRoot, "src", "generated", "players.ts");
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, out);
}

await generatePlayerDirectory();
