import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { TournamentSchema } from "@putting-pals/putting-pals-core";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = __dirname;

const inputPath = path.join(packageRoot, "data/tournaments.json");
const raw = TournamentSchema.pick({ id: true })
  .extend({
    images: TournamentSchema.shape.images.partial().optional(),
  })
  .array()
  .parse(JSON.parse(fs.readFileSync(inputPath, "utf8")));

const idx = {} as Record<string, number>;

raw.forEach((c, i) => {
  idx[c.id] = i;
});

const out = `/** Generated by codegen. Do not edit. */

export const TOURNAMENTS = ${JSON.stringify(raw, null, 2)} as const

export const INDEX = ${JSON.stringify(idx, null, 2)} as const
`;

const outPath = path.join(packageRoot, "src", "generated", "tournaments.ts");
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, out);
