name: ⚡️ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: 🔬 Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Run check
        run: biome ci .

  typecheck:
    name: 🧬 Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run typecheck
        run: pnpm typecheck

  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run build
        run: pnpm build

  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        run: pnpm test
